---
title: "Understand IgScan output format"
author: 
  name: Ian Márquez-López
  email: iamarquez@recerca.clinic.cat
  affiliation: Institut d’Investigacions Biomèdiques August Pi i Sunyer (FRCB-IDIBAPS)
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{IgScan output}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE}
options(rmarkdown.html_vignette.check_title = FALSE)
```

The IgScan workflows—for both bulk NGS and single-cell datasets—produce a detailed output containing valuable immunogenetic information. It is therefore essential to understand the structure of the IgScan output and to correctly interpret the clonal groups defined by the package.

In this vingette, we will go through the different fields in IgScan annotation dataframes, as well as the structure of the metadata in a single cell object that has been combined with IgScan.

### IgScan dataframe structure

The primary output of IgScan workflows is a dataframe containing the immunogenetic characterization at the **sequence/contig** level. In this regard, there are some commonalities and specific differences between the outputs from bulk NGS and single cell modalities.

#### Shared IgScan fields (sequence immunogenetic data)

+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IgScan Field                  | Description                                                                                                                                                                                                                                                 |
+===============================+=============================================================================================================================================================================================================================================================+
| contig_id                     | Sequence identifier in the input data.                                                                                                                                                                                                                      |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Raw_sequence                  | Raw input DNA sequence (the whole contig).                                                                                                                                                                                                                  |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Raw_VDJ_sequence              | Input sequence but delimited from FR1 to FR4 (VDJ).                                                                                                                                                                                                         |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| VDJ_sequence                  | Processed VDJ sequence, meaning that insertions and deletions have been corrected and placed in the *InDels* field.                                                                                                                                         |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IgBlast_Germline_alignment    | Germline alignment obtained from IgBlast. The random nucleotides are masked by Ns.                                                                                                                                                                          |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| VDJ_sequence_correctedCDR3    | VDJ nucleotide sequence with an adjusted CDR3 region length to match the *Consensus_Germline* length of the assigned clonotype. Notably, when the CDR3 length is consistent across all members of the clonotype, this field is identical to *VDJ_sequence*. |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| VDJ_sequence_correctedCDR3_aa | Amino acid translation of the *VDJ_sequence_correctedCDR3* field.                                                                                                                                                                                           |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Consensus_Germline            | Germline nucleotide sequence of the assigned clonotype. It does not contain masked random nucleotides, but includes the random nucleotides from the closest-to-germline somatic sequence within the clonotype.                                              |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Consensus_Germline_aa         | Amino acid translation of the *Consensus_Germline* field.                                                                                                                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| VDJ_genes                     | V, D, and J genes and alleles with highest alignment score.                                                                                                                                                                                                 |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| C_gene                        | C gene with highest alignment score.                                                                                                                                                                                                                        |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Functionality                 | Indicates whether the sequence is productive (in-frame, no stop codons) or unproductive.                                                                                                                                                                    |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Junction_aa                   | Amino acid sequence of the junction region (anchors + CDR3).                                                                                                                                                                                                |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Junction_length               | Length of the junction amino acid sequence.                                                                                                                                                                                                                 |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| V_identity                    | Percentage of identity to the germline of the V region.                                                                                                                                                                                                     |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| VDJ_positions                 | Position indices of each segment of the VDJ sequence (FR1-CDR1-FR2-CDR2-FR3-CDR3-FR4).                                                                                                                                                                      |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| V_length                      | Nucleotide squence length of the V region from FR1 to FR3 (exlcuding CDR3 nucleotides that are part part of the V gene).                                                                                                                                    |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| InDels                        | Detected insertions and deletions within the VDJ region.                                                                                                                                                                                                    |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SampleID                      | Sample identifier (specified by the user in the workflow).                                                                                                                                                                                                  |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Shared IgScan fields (clonal group identifiers)

One of the most important steps in analyzing immune repertoires is clustering sequences into clonal groups. IgScan offers three levels of clonal grouping, each reflecting a distinct biological concept:

-   **Clonotype (C)**: Reflects the concept of *rearrangement-of-origin*, meaning that all cells within a clonotype share sufficiently similar V(D)J rearrangements to be assumed to originate from the same pre-BCR cell.

-   **Clonotype Variant (CV)**: Defines an amino acid CDR3 sequence variant within a clonotype. This concept captures potentially functional variants of a clonotype that arise from somatic mutations in the CDR3 region.

-   **Subclone (S)**: Represents identical nucleotide V(D)J sequences, corresponding to individual somatic hypermutation variants within a clonotype or clonotype variant.

Based on these definitions, IgScan provides the following fields in its output:

+----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ClonotypeID                | Clonotype identifier composed of the *locus* and a numeric rank indicating the abundance of the clone in the sample (e.g. IGH.C1).                                                               |
+----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Clonotype_Consensus_CDR3aa | Consensus CDR3 amino acid sequence of the assigned clonotype, representing the most common CDR3 variant among all sequences within the clone and accounting for intraclonal genetic variability. |
+----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ClonotypeVariantID         | Clonotype variant identifier composed of the *ClonotypeID* and a numeric rank indicating the abundance of the clonotype variant in the clonotype (e.g. IGH.C1.CV1).                              |
+----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SubcloneID                 | Subclone identifier composed of the *ClonotypeVariantID* and a numeric rank indicating the abundance of the subclone variant in the clonotype variant (e.g. IGH.C1.CV1.S1).                      |
+----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SubcloneID_in_Clonotype    | Subclone identifier composed of the *ClonotypeID* and a numeric rank indicating the abundance of the subclone variant in the clonotype (e.g. IGH.C1.1).                                          |
+----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Bulk NGS IgScan fields (sequence abundance information)

In bulk NGS data, it is important to retain both the total count and relative abundance of each identified group of sequences, as these metrics help characterize the architecture of the analyzed BCR repertoire. For this reason, the IgScan bulk NGS workflow includes the following fields in its output:

+-----------------------------------+---------------------------------------------------------------------------+
| IgScan Field                      | Description                                                               |
+===================================+===========================================================================+
| Clonotype_nReads                  | Total number of reads of the clonotype.                                   |
+-----------------------------------+---------------------------------------------------------------------------+
| Clonotype_freq                    | Relative frequency of the clonotype within the sample.                    |
+-----------------------------------+---------------------------------------------------------------------------+
| ClonotypeVariant_nReads           | Total number of reads of the clonotype variant.                           |
+-----------------------------------+---------------------------------------------------------------------------+
| ClonotypeVariant_freq             | Relative frequency of the clonotype variant within the clonotype.         |
+-----------------------------------+---------------------------------------------------------------------------+
| Subclone_nReads                   | Total number of reads of the subclone (unique VDJ nucleotide sequence).   |
+-----------------------------------+---------------------------------------------------------------------------+
| Subclone_freq_in_ClonotypeVariant | Relative frequency of the subclone within its specific clonotype variant. |
+-----------------------------------+---------------------------------------------------------------------------+
| Subclone_freq_in_Clonotype        | Relative frequency of the subclone within the whole clonotype.            |
+-----------------------------------+---------------------------------------------------------------------------+

#### Single cell IgScan fields (information at the cell level)

When analyzing single-cell data, annotation at the contig level is not sufficient. Instead, contigs coming from the same cell must be combined to fully reconstruct the BCR of each individual cell.

Importantly, users should be aware that IgScan performs a strict evaluation of cell-level information to assess the completeness of the identified BCR. This evaluation also supports the detection of potential doublets. The results are stored in the completeBCR field, which can take on different values depending on the observed BCR configuration:

-   **Yes**: A functional combination of heavy and light chains compatible with the allelic capacity of a single cell. The typical case involves one heavy and one light chain (e.g., IGH-IGK), but biallelic rearrangements are also supported (e.g., IGH-IGK1-IGK2).

-   **Single_chain_1 / Single_chain_2**: Cells with one or two sequences detected, but only from either the heavy OR the light chain. These are often partial observations of complete ("Yes") clonotypes and can be re-assigned using the function `IgScan::rescue_single_chain_cells()`.

-   **Alternative_clonotype:** A complete BCR (at least one heavy and one light chains) that is a subset of another complete ("Yes") clonotype observed at higher frequency. For example, if the dominant clonotype is IGH.C1-IGK.C1-IGK.C2 (biallelic kappa rearrangement), then IGH.C1-IGK.C1 or IGH.C1-IGK.C2 would be flagged as alternative clonotypes.

-   **Clonotype_doublet**: A combination of chains belonging to two different complete ("Yes") clonotypes. For instance, if C1 = **IGH.C1-IGK.C1** and C2 = [IGH.C2-IGL.C1]{.underline}, then a cell with **IGH.C1**-[IGL.C1]{.underline} or [IGH.C2]{.underline}-**IGK.C1** would be flagged as a clonotype doublet.

-   **Repeated_chain:** A cell in which the same clonotype appears more than once. This suggests a potential doublet involving two cells of the same clonotype. For example, if C1 = IGH.C1-IGL.C1, a repeated chain case would be IGH.C1-IGH.C1-IGL.C1. These are generally recommended for removal.

-   **Not_supported**: Configurations with 3 or 4 rearranged chains that do not form a valid BCR (e.g., three distinct light chains) or more than four total contigs, which exceeds the allelic limit of a single cell.

-   **Yes_rescue**: A cell originally classified as *Single_chain_1* or *Single_chain_2* that has been re-assigned to a known clonotype via `IgScan::rescue_single_chain_cells()`.

The IgScan single-cell workflow includes the following fields that provide annotation at the cell level:

+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IgScan Field                         | Description                                                                                                                                                                                                 |
+======================================+=============================================================================================================================================================================================================+
| completeBCR                          | Specifies the completeness status of the BCR in the current cell (see explanation above).                                                                                                                   |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igClonotypeID_num                    | Simplified identifier representing a specific combination of heavy and light chain clonotypes, assigned a numeric rank based on the clonotype abundance within the sample (e.g. C1).                        |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igClonotypeID                        | *ClonotypeID* from each chain identified in the cell separated by dashes (e.g. IGH.C1-IGK.C1).                                                                                                              |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igClonotypeVariantID_num             | Simplified identifier representing a specific combination of heavy and light chain clonotype variants, assigned a numeric rank based on the clonotype variant abundance within the clonotype (e.g. C1.CV1). |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igClonotypeVariantID                 | *ClonotypeVariantID* from each chain identified in the cell separated by dashes (e.g. IGH.C1.CV1-IGK.C1.CV1).                                                                                               |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igSubcloneID_in_ClonotypeVariant_num | Simplified identifier representing a specific combination of heavy and light chain subclones, assigned a numeric rank based on the subclone abundance within its clonotype variant (e.g. C1.CV1.S1).        |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igSubcloneID_in_Clonotype_num        | Simplified identifier representing a specific combination of heavy and light chain subclones, assigned a numeric rank based on the subclone abundance within its clonotype (e.g. C1.1).                     |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igSubcloneID                         | *SubcloneID* from each chain identified in the cell separated by dashes (e.g. IGH.C1.CV1.S1-IGK.C1.CV1.S1).                                                                                                 |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igRaw_VDJ_sequence                   | *Raw_VDJ_sequence* from each chain identified in the cell separated by underscores.                                                                                                                         |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igVDJ_sequence                       | *VDJ_sequence* from each chain identified in the cell separated by underscores.                                                                                                                             |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igVDJ_sequence_aa                    | *VDJ_sequence_aa* from each chain identified in the cell separated by underscores.                                                                                                                          |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igClonotype_Consensus_Germline       | *Clonotype_Consensus_Germline* from each chain identified in the cell separated by underscores.                                                                                                             |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igClonotype_Consensus_Germline_aa    | *Clonotype_Consensus_Germline_aa* from each chain identified in the cell separated by underscores.                                                                                                          |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igVDJ_positions                      | *VDJ_positions* from each chain identified in the cell separated by underscores.                                                                                                                            |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igInDels                             | *InDels* from each chain identified in the cell separated by dashes.                                                                                                                                        |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| igClonotype_Consensus_CDR3aa         | *Clonotype_Consensus_CDR3aa* from each chain identified in the cell separated by underscores.                                                                                                               |
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

It is important to note that simplified identifiers (i.e., those ending in **\_num**) are only assigned to cells with a valid or interpretable BCR configuration. Specifically, they are present only when the *completeBCR* field is set to "**Yes**", "**Alternative_clonotype**", or "**Yes_rescue**". Cells with incomplete or problematic BCRs do not receive these identifiers.

### Structure of IgScan in single-cell objects

Now that we understand how to interpret the different fields in the IgScan output format, it is important to note how this information is structured when integrated into a single-cell object. When an IgScan output is added to the metadata of a single-cell object, the structure of the dataframe is the following:

+:-------------------------------:+:-------------------------:+:-------------------------:+:-------------------------:+:-------------------------:+:-------------------------:+
| **Previously existing metadta** | **IgScan**                | **IgScan**                | **IgScan**                | **IgScan**                | **IgScan**                |
|                                 |                           |                           |                           |                           |                           |
|                                 | **Cell level annotation** | **IGH1 contig anotation** | **IGH2 contig anotation** | **IGL1 contig anotation** | **IGL2 contig anotation** |
+---------------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+

As can be seen, IgScan annotations are appended to the right side of the single-cell metadata in a structured manner, following this order:

-   **Cell level annotation:** This section includes the *completeBCR* field and the combined immunogenetic information derived from all chains detected in a given cell. All fields in this section are prefixed with a lowercase ***ig*** (e.g., igRaw_VDJ_sequence), and represent a summarized, per-cell view of the BCR.

-   **Contig level annotation:** This section provides detailed information for each individual chain identified, including fields such as VDJ and C gene usage, V gene identity (%), functionality, junction amino acid sequence, and more. Since IgScan supports biallelic rearrangements, the contig-level information is organized into **four distinct blocks**:

    -   Two blocks for the potentially rearranged **heavy chains**

    -   Two blocks for the potentially rearranged **light chains** (kappa or lambda)

    Each block corresponds to one possible V(D)J rearrangement observed in the cell, allowing for full reconstruction of both monoallelic and biallelic configurations.
