#' Run IgBlast on raw NGS data
#'
#' @description This function processes raw sequencing data and runs IgBLAST to perform
#' immunoglobulin reannotation using the IMGT databases. The function supports
#' multiple input formats and generates annotated outputs, including reports
#' if wanted by the user.
#'
#' @param sample_paths A vector of paths to input files or a vector of
#' directories containing the input file. Supported formats depend on the
#' `input_format` parameter.
#' @param sample_labels A vector of sample labels corresponding to `sample_paths`.
#'   Must have the same length as `sample_paths`.
#' @param input_format A string specifying the format of the input data, currently supporting:
#' '10xBCR_fasta', '10xBCR_csv', 'ParseBCR', 'BDRhapsodyBCR', 'MiXCR',
#' 'TRUST4', 'AIRR', 'IMGT_AIRR' and 'fasta'.
#' @param data_type A string indicating the type of data. Options: 'single_cell' and 'bulk'. Default is 'single_cell'.
#' @param outputDir The directory to store intermediate and output files.
#'   Defaults to the working directory if not provided.
#' @param annotate_C Logical. If `TRUE`, the function includes the annotation of
#'   constant regions using the NCBI IG C region database.
#' @param threads An integer specifying the number of threads for processing samples.
#'   Default is 1.
#' @param threads_IgBlast An integer specifying the number of threads for running IgBLAST.
#'   Default is 1.
#' @param Evalue_cutoff A numeric value specifying the E-value cutoff for IgBLAST alignment.
#'   Default is `NULL` (no cutoff applied).
#' @param run_IgBlast_report Logical. If `TRUE`, generates a PDF report summarizing
#'   IgBLAST results.
#'
#' @return A list containing the paths of all generated IgBLAST output files. If
#'   `run_IgBlast_report = TRUE`, also includes the path to the PDF report.

#' @details
#' This function performs the following steps:
#'
#'    1. Validates the input data and format.
#'
#'    2. Converts input data to FASTA format if needed.
#'
#'    3. Runs IgBLAST for V(D)J-(C) reannotation and alignment.
#'
#'    4. Generates an IgBlast summary report if specified.
#'
#' @export
#'
#' @note Ensure that IgBLAST and its required reference databases are installed and
#'   properly configured before running this function.
#'
#' @examples
#' \dontrun{
#' # Example 1: Running IgBLAST with FASTA inputs
#' Run_IgBlast_from_RawData(
#'   sample_paths = list("path/to/sample1.fasta", "path/to/sample2.fasta"),
#'   sample_labels = c("Sample1", "Sample2"),
#'   input_format = "fasta",
#'   data_type = "single_cell",
#'   outputDir = "path/to/outDir")
#'
#' # Example 2: Running IgBLAST with 10x Genomics CSV inputs and generating a IgBlast report
#' Run_IgBlast_from_RawData(
#'   sample_paths = list("path/to/sample1_filtered_contig_annotations.csv"),
#'   sample_labels = c("Sample1"),
#'   input_format = "10xbcr_csv",
#'   data_type = "single_cell",
#'   outputDir = "path/to/outDir",
#'   run_IgBlast_report = TRUE)
#' }
#'
Run_IgBlast_from_RawData <- function(sample_paths, sample_labels, input_format, data_type = "single_cell", Evalue_cutoff = NULL, annotate_C = T, threads_IgBlast = 1, outputDir = NULL, run_IgBlast_report = F, threads = 1){

  ## First checks
  if(length(sample_paths) == 0){stop("No sample names have been provided. Try not to give empty vectors!")}
  if(length(sample_labels) > 0 & length(sample_paths) != length(sample_labels)){stop("'sample_paths' has different length than 'sample_labels'. Please, check both input vectors!")}

  ## Setting global variables such as outputDir, IgBlast directory, OS, etc.
  IgBlastPath <- paste0(system.file("IgBlast", package = "IgScan", mustWork = T), "/")
  IgBlastRef <- paste0(IgBlastPath, "Reference/")
  if(tolower(Sys.info()["sysname"]) == "linux"){
    IgBlastDir <- paste0(IgBlastPath, "Linux/")
  } else if (tolower(Sys.info()["sysname"]) == "darwin"){
    IgBlastDir <- paste0(IgBlastPath, "Mac/")
  } else{stop("IgScan only works for Linux or Mac operating systems.")}
  Sys.setenv(IGDATA = IgBlastDir)

  ## Put the input_format in lower case and check if it has been correctly set
  input_format <- tolower(input_format)
  if(!input_format %in% c("10xbcr_fasta", "10xbcr_csv", "parsebcr", "bdrhapsodybcr", "mixcr", "trust4", "airr", "imgt_airr", "fasta")){stop("Invalid value for 'input_format'. It should be either '10xbcr_fasta', '10xbcr_csv', 'parsebcr', 'bdrhapsodybcr', 'mixcr', 'trust4', 'airr', 'imgt_airr' or 'fasta'.")}

  ## Create names for each sample if they have not been indicated by the user
  if(length(sample_labels) == 0){sample_labels <- paste0("sample", seq_along(sample_paths))}

  ## Create a dynamic tmp directory to store all the files generated by the package
  if(is.null(outputDir)){
    outputDir <- paste0("./", format(Sys.time(), "%d-%m-%Y_%H%M%S-IgScanResults/"))
    n <- 1
    while(TRUE){
      if(dir.exists(outputDir)){
        outputDir <- gsub("-IgScanResults.*/", paste0("-IgScanResults_",n,"/"), outputDir)
        n <- n+1
      } else{break}
    }
    system(paste0("mkdir ",outputDir))
    warning(paste0("Output directory has been set to ", outputDir), call. = FALSE)
  }

  ## Creating the different directories within the tmp Dir
  system(paste0("mkdir ",outputDir,"fasta_inputs/"))
  system(paste0("mkdir ",outputDir,"igblast_outs/"))

  ## Read Input Files
  samples_list <- .load_RawData(sample_paths, input_format)

  ## Write IgBlast fasta inputs
  .write_fasta_from_RawData(samples_list, sample_labels, outputDir, input_format, data_type, threads)

  ## Run IgBlast in parallel for all samples
  .runIgBLAST_Parallel(sample_labels, outputDir, IgBlastDir, IgBlastRef, Evalue_cutoff, annotate_C, threads_IgBlast, run_IgBlast_report, threads)

  return(samples_list)
}

.load_RawData <- function(sample_paths, input_format){

  input_format <- tolower(input_format)
  if(!input_format %in% c("10xbcr_fasta", "10xbcr_csv", "parsebcr", "bdrhapsodybcr", "mixcr", "trust4", "airr", "imgt_airr", "fasta")){stop("Invalid value for 'input_format'. It should be either '10xbcr_fasta', '10xbcr_csv', 'parsebcr', 'bdrhapsodybcr', 'mixcr', 'trust4', 'airr', 'imgt_airr' or 'fasta'.")}

  info <- file.info(sample_paths)

  sample_paths_read <- c()
  for(row in 1:nrow(info)){
    if(info$isdir[row]){
      sample_paths_read <- c(sample_paths_read, list.files(rownames(info)[row], full.names = T, recursive = F))
    } else{
      if(!file.exists(rownames(info)[row])){stop(paste0("File ", rownames(info)[row], " does not exist!"))}
      sample_paths_read <- c(sample_paths_read, rownames(info)[row])
    }
  }

  samples_list <- list()
  for(i in 1:length(sample_paths_read)){
    if(input_format %in% c("10xbcr_fasta", "fasta")){
      tmp <- sample_paths_read[i]
    }
    else if(input_format %in% c("mixcr", "bdrhapsodybcr", "parsebcr", "trust4", "airr", "imgt_airr")){
      tmp <- fread(sample_paths_read[i], header = T, sep = "\t", stringsAsFactors = F, data.table = F)
    }
    else if(input_format == "10x_csv"){
      tmp <- fread(sample_paths_read[i], header = T, sep = ",", stringsAsFactors = F, data.table = F)
    }
    samples_list[[i]] <- tmp
  }
  return(samples_list)
}

.write_fasta_from_RawData <- function(samples_list, sample_labels, outputDir, input_format, data_type, threads){

  mclapply(1:length(samples_list), function(i) {

    fasta_file <- paste0(outputDir,"fasta_inputs/",sample_labels[i],"_igblast_in.fa")

    if(input_format %in% c("10xbcr_fasta", "fasta")){
      system(paste0("cp ", samples_list[[i]]," ", fasta_file))
    }

    else if(input_format == "10xbcr_csv"){
      samples_list[[i]]$VDJseq <- paste0(samples_list[[i]]$fwr1_nt,samples_list[[i]]$cdr1_nt,samples_list[[i]]$fwr2_nt,samples_list[[i]]$cdr2_nt,samples_list[[i]]$fwr3_nt,samples_list[[i]]$cdr3_nt,samples_list[[i]]$fwr4_nt)
      for(row in 1:nrow(samples_list[[i]])){write(paste0(">",samples_list[[i]]$contig_id[row],"\n",samples_list[[i]]$VDJseq[row]), file = fasta_file, append = T)}
    }

    else if(input_format == "mixcr"){
      samples_list[[i]]$VDJseq <- gsub(",", "" , samples_list[[i]]$targetSequences)
      samples_list[[i]]$Chain <- sapply(samples_list[[i]]$allVHitsWithScore, function(x) substr(x, 1, 3))
      samples_list[[i]]$cloneId <- ifelse(all(grepl("^[0-9]+$", samples_list[[i]]$cloneId)), paste0(sample_labels[i], samples_list[[i]]$Chain, "_", samples_list[[i]]$cloneId), samples_list[[i]]$cloneId)

      if(data_type == "single_cell"){
        samples_list[[i]]$SeqID <- paste0(samples_list[[i]]$cloneId)
      } else if(data_type == "bulk"){
        samples_list[[i]]$SeqID <- paste0(samples_list[[i]]$cloneId, "=", samples_list[[i]]$cloneCount)
      }
      for(row in 1:nrow(samples_list[[i]])){write(paste0(">",samples_list[[i]]$SeqID[row],"\n",samples_list[[i]]$VDJseq[row]), file = fasta_file, append = T)}
    }

    else if(input_format %in% c("bdrhapsodybcr", "parsebcr", "trust4", "airr", "imgt_airr")){
      samples_list[[i]] <- samples_list[[i]][samples_list[[i]]$locus %in% c("IGH", "IGK", "IGL"),]
      samples_list[[i]]$VDJseq <- samples_list[[i]]$sequence

      if(data_type == "single_cell"){
        for(row in 1:nrow(samples_list[[i]])){write(paste0(">",samples_list[[i]]$sequence_id[row], "\n",samples_list[[i]]$VDJseq[row]), file = fasta_file, append = T)}
      } else if(data_type == "bulk"){
        for(row in 1:nrow(samples_list[[i]])){write(paste0(">",samples_list[[i]]$sequence_id[row], "=", samples_list[[i]]$consensus_count[row], "\n",samples_list[[i]]$VDJseq[row]), file = fasta_file, append = T)}
      }
    }

    return(paste0(input_format, " --> Fasta for sample ", sample_labels[i], " has been succesfully completed."))
  }, mc.cores = threads)
}

.runIgBLAST <- function(input, output, IgBlastDir, IgBlastRef, Evalue_cutoff, annotate_C, threads_IgBlast){
  command <- paste0(IgBlastDir,"bin/igblastn -germline_db_V ",IgBlastRef,"db/IMGT_HomoSapiens_IG_V.fasta.txt -germline_db_J ",
                    IgBlastRef,"db/IMGT_HomoSapiens_IG_J.fasta.txt -germline_db_D ",IgBlastRef,
                    "db/IMGT_HomoSapiens_IG_D.fasta.txt -organism human -ig_seqtype Ig -auxiliary_data ",
                    IgBlastRef, "optional_file/human_gl.aux -show_translation -outfmt 19 ",
                    ifelse(annotate_C == T, paste0("-c_region_db ", IgBlastRef, "db/ncbi_human_c_genes "), ""),
                    "-num_alignments_D 1 -num_threads ", threads_IgBlast, " -extend_align5end -extend_align3end",
                    ifelse(is.null(Evalue_cutoff), "", paste0("--evalue ", Evalue_cutoff)), " -query ", input," > ", output)

  system(command)
}

.runIgBLAST_Parallel <- function(sample_labels, outputDir, IgBlastDir, IgBlastRef, Evalue_cutoff, annotate_C, threads_IgBlast, run_IgBlast_report, threads){

  if(threads_IgBlast > threads){threads_IgBlast <- threads}

  input_files <- paste0(outputDir,"fasta_inputs/",sample_labels,"_igblast_in.fa")
  output_files <- paste0(outputDir,"igblast_outs/",sample_labels,"_igblast_out.tsv")

  mclapply(1:length(input_files), function(i) {
    .runIgBLAST(input_files[i], output_files[i], IgBlastDir, IgBlastRef, Evalue_cutoff, annotate_C, threads_IgBlast)
    if(run_IgBlast_report == T){ .IgBLAST_Report(output_files[i], paste0(outputDir,"igblast_outs/")) }
  }, mc.cores = threads)
}

.IgBLAST_Report <- function(igblast_out, igblast_outDir){

  outID <- gsub("_igblast_out.tsv", "", basename(igblast_out))

  color_vector <- c("IGH" = "#ACA6DD", "IGK" = "#FEDB71", "IGL" = "#7DA182",
                    "Productive" = "#C0DE92", "No" = "#C0DE92", "Complete" = "#C0DE92",
                    "Unproductive" = "#D8696F", "Yes" = "#D8696F", "Uncomplete" = "#D8696F")

  df <- fread(igblast_out, header = T, sep = "\t", stringsAsFactors = F, data.table = F)

  df <- df[, c("locus", "productive", "stop_codon", "v_frameshift", "complete_vdj",
               "v_call", "cdr3_aa", "v_score", "d_score", "j_score", "c_score")]

  df$locus <- factor(df$locus, levels = c("IGH", "IGK", "IGL"))

  df$productive <- ifelse(df$productive %in% c(T, "T"), "Productive", "Unproductive")
  df$productive <- factor(df$productive, levels = c("Productive", "Unproductive"))
  df$stop_codon <- ifelse(df$stop_codon %in% c(F, "F"), "No", "Yes")
  df$stop_codon <- factor(df$stop_codon, levels = c("No", "Yes"))
  df$v_frameshift <- ifelse(df$v_frameshift %in% c(F, "F"), "No", "Yes")
  df$v_frameshift <- factor(df$v_frameshift, levels = c("No", "Yes"))
  df$complete_vdj <- ifelse(df$complete_vdj %in% c(T, "T"), "Complete", "Uncomplete")
  df$complete_vdj <- factor(df$complete_vdj, levels = c("Complete", "Uncomplete"))

  df$Vgene <- unname(sapply(df$v_call, function(v) paste0(unique(sapply(strsplit(v, ",")[[1]], function(x) strsplit(x, "\\*")[[1]][1])), collapse = ",")))
  df$clonotypeLabel <- paste(df$Vgene, df$cdr3_aa, sep = "_")

  ## Plot A:
  fun_df <- data.frame()
  stp_df <- data.frame()
  frsh_df <- data.frame()
  compl_df <- data.frame()
  for(chain in c("IGH", "IGK", "IGL")){
    if(!chain %in% df$locus){next}

    fun <- data.frame(table(df$productive[df$locus == chain]))
    fun$chain <- chain
    fun$relFreq <- fun$Freq/sum(fun$Freq)*100
    fun_df <- rbind(fun_df, fun)

    stp <- data.frame(table(df$stop_codon[df$locus == chain]))
    stp$chain <- chain
    stp$relFreq <- stp$Freq/sum(stp$Freq)*100
    stp_df <- rbind(stp_df, stp)

    frsh <- data.frame(table(df$v_frameshift[df$locus == chain]))
    frsh$chain <- chain
    frsh$relFreq <- frsh$Freq/sum(frsh$Freq)*100
    frsh_df <- rbind(frsh_df, frsh)

    compl <- data.frame(table(df$complete_vdj[df$locus == chain]))
    compl$chain <- chain
    compl$relFreq <- compl$Freq/sum(compl$Freq)*100
    compl_df <- rbind(compl_df, compl)
  }

  pA1 <- ggplot(fun_df, aes(x = chain, y = relFreq, fill = Var1)) +
    geom_bar(stat = "identity", position = "stack", color = "black", linewidth = 0.3) +
    theme_classic() + labs(x = "", y = "Frequency (%)\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    ggtitle(label = "Productive vs. Unproductive") +
    theme(plot.title = element_text(hjust = 0.5))

  pA2 <- ggplot(stp_df, aes(x = chain, y = relFreq, fill = Var1)) +
    geom_bar(stat = "identity", position = "stack", color = "black", linewidth = 0.3) +
    theme_classic() + labs(x = "", y = "Frequency (%)\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    ggtitle(label = "Stop codons in VDJ") +
    theme(plot.title = element_text(hjust = 0.5))

  pA3 <- ggplot(frsh_df, aes(x = chain, y = relFreq, fill = Var1)) +
    geom_bar(stat = "identity", position = "stack", color = "black", linewidth = 0.3) +
    theme_classic() + labs(x = "", y = "Frequency (%)\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    ggtitle(label = "Frameshift V gene") +
    theme(plot.title = element_text(hjust = 0.5))

  pA4 <- ggplot(compl_df, aes(x = chain, y = relFreq, fill = Var1)) +
    geom_bar(stat = "identity", position = "stack", color = "black", linewidth = 0.3) +
    theme_classic() + labs(x = "", y = "Frequency (%)\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    ggtitle(label = "Complete vs. Uncomplete VDJ") +
    theme(plot.title = element_text(hjust = 0.5))

  ## Plot B:
  score_df <- df[, c("locus", "v_score", "d_score", "j_score", "c_score")]
  score_df <- reshape(score_df,
                      varying = list(c("v_score", "d_score", "j_score", "c_score")),
                      v.names = "Score_Value",
                      timevar = "Score_Type",
                      times = c("v_score", "d_score", "j_score", "c_score"),
                      direction = "long")

  locus_df <- as.data.frame(table(df$locus))
  locus_df$Var1 <- factor(locus_df$Var1, levels = c("IGH", "IGK", "IGL"))
  pB0 <- ggplot(locus_df[locus_df$Freq > 0,], aes(x = Var1, y = Freq, fill = Var1)) +
    geom_bar(stat = "identity", color = "black", linewidth = 0.3) +
    theme_classic() + labs(x = "", y = "Number of contigs\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    theme(legend.position = "none")

  pB1 <- ggplot(score_df[score_df$Score_Type == "v_score",], aes(x = locus, y = Score_Value, fill = locus)) +
    geom_violin() + geom_jitter(width = 0.1, height = 0, size = 0.5) +
    theme_classic() + labs(x = "", y = "IgBLAST alignment score\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    ggtitle(label = "V gene Alignment Score") +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "none")

  pB2 <- ggplot(score_df[score_df$Score_Type == "d_score" & score_df$locus == "IGH",], aes(x = locus, y = Score_Value, fill = locus)) +
    geom_violin() + geom_jitter(width = 0.1, height = 0, size = 0.5) +
    theme_classic() + labs(x = "", y = "IgBLAST alignment score\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    ggtitle(label = "D gene Alignment Score") +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "none")

  pB3 <- ggplot(score_df[score_df$Score_Type == "j_score",], aes(x = locus, y = Score_Value, fill = locus)) +
    geom_violin() + geom_jitter(width = 0.1, height = 0, size = 0.5) +
    theme_classic() + labs(x = "", y = "IgBLAST alignment score\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    ggtitle(label = "J gene Alignment Score") +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "none")

  pB4 <- ggplot(score_df[score_df$Score_Type == "c_score",], aes(x = locus, y = Score_Value, fill = locus)) +
    geom_violin() + geom_jitter(width = 0.1, height = 0, size = 0.5) +
    theme_classic() + labs(x = "", y = "IgBLAST alignment score\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    ggtitle(label = "C gene Alignment Score") +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "none")

  ## Plot C: Estimation of clonality
  clonality_df <- aggregate(x = df$clonotypeLabel, by = list(df$clonotypeLabel), FUN = length)
  clonality_df <- clonality_df[order(clonality_df$x, decreasing = T),]
  clonality_df$locus <- df$locus[match(clonality_df$Group.1, df$clonotypeLabel)]

  clonality_df <- rbind(clonality_df[clonality_df$x > 1,],
                        c("Unique_IGH", nrow(clonality_df[clonality_df$x == 1 & clonality_df$locus == "IGH",]), "IGH"),
                        c("Unique_IGK", nrow(clonality_df[clonality_df$x == 1 & clonality_df$locus == "IGK",]), "IGK"),
                        c("Unique_IGL", nrow(clonality_df[clonality_df$x == 1 & clonality_df$locus == "IGL",]), "IGL"))

  colnames(clonality_df) <- c("Clonal_group", "Count", "Locus")
  clonality_df$ClonalID <- ifelse(startsWith(clonality_df$Clonal_group, "Unique_"),
                                  clonality_df$Clonal_group,
                                  paste0(as.character(clonality_df$Locus), ".", ave(as.character(clonality_df$Locus), as.character(clonality_df$Locus), FUN = seq_along)))
  clonality_df <- clonality_df[clonality_df$Count > 0,]
  clonality_df$ClonalID <- factor(clonality_df$ClonalID, levels = clonality_df$ClonalID)
  clonality_df$Locus <- factor(clonality_df$Locus, levels = c("IGH", "IGK", "IGL"))

  pC <- ggplot(clonality_df, aes(x = ClonalID, y = as.numeric(Count), fill = Locus)) +
    geom_bar(stat = "identity", color = "black", linewidth = 0.3) +
    theme_classic() + labs(x = "Clonal group", y = "Number of contigs\n", fill = "") +
    scale_fill_manual(values = color_vector) +
    ggtitle(label = "Distribution of clonal rearrangements") +
    theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 45, hjust = 1))

  layout <- (pA1 | pA2 | pA3 | pA4) / (pB0 | pB1 | pB2 | pB3 | pB4) / pC
  ggsave(paste0(igblast_outDir, outID, "_IgBLAST_report.pdf"), plot = layout, width = 14, height = 13, units = "in")

  write("Dictionary of the corresponding IGVgene_CDR3aa for each clonal group:", file = paste0(igblast_outDir, outID, "_IgBLAST_report.txt"))
  for(i in 1:nrow(clonality_df)){
    write(paste0(clonality_df$ClonalID[i], " --> ", clonality_df$Clonal_group[i]), file = paste0(igblast_outDir, outID, "_IgBLAST_report.txt"), append = T)
  }
}
